### ISSUE TITLE
关于一个LANR_NLM中一个公式的问题(纯学术疑问)

### ISSUE THREAD

**Issue by dundee98** [junjun-jiang/LANR-NLM#1]
您好，我在看您的论文《Single Image Super-Resolution via Locally Regularized Anchored Neighborhood Regression and Nonlocal Means》有一个疑惑，就是在您提出的算法1中的第8步，关于corr(yi,DL)，请问你具体使用的什么公式计算的相关系数呢，是用的互相关系数吗，我看论文呢中没有具体说，希望大佬可以帮忙解惑（万分感谢！！！求指点）

**Comment by dundee98** [comment]
我不太明白为什么惩罚项前面权重g,要是相关性系数的倒数

**Comment by junjun-jiang** [comment]
> 您好，我在看您的论文《Single Image Super-Resolution via Locally Regularized Anchored Neighborhood Regression and Nonlocal Means》有一个疑惑，就是在您提出的算法1中的第8步，关于corr(yi,DL)，请问你具体使用的什么公式计算的相关系数呢，是用的互相关系数吗，我看论文呢中没有具体说，希望大佬可以帮忙解惑（万分感谢！！！求指点）
抱歉，你提的issue今天才有邮件提醒我。

**Comment by junjun-jiang** [comment]
> 我不太明白为什么惩罚项前面权重g,要是相关性系数的倒数

相关性越大，说明yi与字典中原子的相似性就大，这时如果给他一个小的惩罚gi，wi取得大也比较“安全”了。

**Comment by dundee98** [comment]
大佬你好，我看这个代码是做的三倍的，如果做二倍的是否需要改demo里面的除了upscale以外的其他参数
